export const STATE_PORT = 9000;
export const GOAL_PORT = 9001;
export const TARGET_PORT = 9002;
export const HOME_RESERVE_PORT = 9003;

export const ENUM_PID_PORT = 8000;
export const TRADE_MONITOR_PORT = 8001;
export const TRADE_TOTAL_PROFIT_PORT = 8002;
export const TRADE_TRANSACTIONS_PORT = 8003;
export const SERVER_RAM_PORT = 8004;
export const IPVGO_MONITOR_PORT = 8005;
export const C2C_MONITOR_PORT = 8006;

export const ALL_PORTS = [
  STATE_PORT,
  GOAL_PORT,
  TARGET_PORT,
  HOME_RESERVE_PORT,
  ENUM_PID_PORT,
  TRADE_MONITOR_PORT,
  TRADE_TOTAL_PROFIT_PORT,
  SERVER_RAM_PORT,
  IPVGO_MONITOR_PORT,
  C2C_MONITOR_PORT,
];
